rf_params:
  n_estimators: 300
  max_depth: null
  min_samples_split: 10
  min_samples_leaf: 4
  random_state: 42

cb_params:
  iterations: 300
  depth: 6
  learning_rate: 0.05
  random_state: 42

cb_quantile_params: ${cb_params}

xgb_params:
  n_estimators: 300
  max_depth: 6
  learning_rate: 0.05
  random_state: 42

lgbm_params:
  n_estimators: 300
  learning_rate: 0.05
  num_leaves: 15
  max_depth: 6
  min_data_in_leaf: 30
  random_state: 42

cb_alpha_low: 0.1
cb_alpha_median: 0.5
cb_alpha_high: 0.9
