cb_params:
  iterations: 300
  depth: 6
  learning_rate: 0.05
  random_state: 42

xgb_params:
  n_estimators: 300
  max_depth: 6
  learning_rate: 0.05
  random_state: 42

xgb_param_grid:
  n_estimators: [100, 200]
  max_depth: [3, 5]
  learning_rate: [0.05, 0.1]
