cv_folds: 2

xgb_param_grid:
  n_estimators: [100, 200]
  max_depth: [3, 5]
  learning_rate: [0.05, 0.1]

cb_param_grid:
  depth: [4, 6]
  iterations: [100, 200]
  learning_rate: [0.05, 0.1]

pca_n_components: 5

ridge_pca_param_grid:
  alpha: [0.01, 0.1, 1, 10, 100]
  n_components: [5, 10, 20]

ridge_cv_folds: 2